server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: user-service
          uri: lb://user-service
          predicates: [ Path=/api/users/** ]
          filters: [ StripPrefix=0 ]
        - id: trip-service
          uri: lb://trip-service
          predicates: [ Path=/api/trips/** ]
          filters: [ StripPrefix=0 ]
        - id: reservation-service
          uri: lb://reservation-service
          predicates: [ Path=/api/reservations/** ]
          filters: [ StripPrefix=0 ]
      discovery:
        locator:
          enabled: true
  main:
    web-application-type: reactive
jwt:
  secret: ${JWT_SECRET:dev_jwt_secret_change_me}
  expirationMs: 86400000
management:
  endpoints:
    web:
      exposure:
        include: health,info
