server:
  port: 8761
spring:
  application:
    name: eureka-server
management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.security: TRACE
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
