server:
  port: 8082
spring:
  application:
    name: trip-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/tripdb}
    username: ${SPRING_DATASOURCE_USERNAME:trip}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET:change-me-in-docker-compose}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.security: TRACE
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
